SDK basic tasks
contentauth/opensource.contentauth.org pull request #176
Opened 2024-11-14 20:10 UTC by crandmck

## Changes in this pull request

Clarify and document new API and add manifest tasks.  

**Top-level view: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/**

Developers should review the languages that they work on. Do we need further reviewers?

For information on where all the files are, see **Notes** at the bottom of this description.

NOTES:

Removed JS and Node for now.  These can come in subsequent PR.

- Reading and verifying manifest data
- Creating parent ingredient with intents and defaults
  - Provide source as parent
  - Sign with an additional assertion, e.g. publish
- Archiving and unarchiving
- Using builder intents

Probably don't need to include "Selective manifest construction". Not common for most ppl.

### Rust 

@ok-nick and/or @gpeacock to review

- Reading manifest data: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read?lang=rust
- Getting resources from a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources?lang=rust
- Attaching and signing a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build?lang=rust

### C++

@tmathern  and/or @gpeacock to review

- Reading manifest data: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read?lang=cpp
- Getting resources from a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources?lang=cpp
- Attaching and signing a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build?lang=cpp

### Python 

@tmathern to review 

- Reading manifest data: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read?lang=python
- Getting resources from a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources?lang=python
- Attaching and signing a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build?lang=python

## Notes

To make reviewing easier for developers, I moved all the code into separate files in the `docs/tasks` sub-directories:  `cpp`, `python`, and `rust`. 

Each language has files for each task:

- Reading manifest data: `_<lang>-read.md`
- Getting resources from a manifest: `_<lang>-get-resources.md`
- Attaching a manifest to an asset and signing it: `_<lang>-build.md`

2025-02-14 20:08 UTC, tmathern requested changes
**Needs changes:**
https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources/?lang=python
The indentation of the code example is off, and indentation is important for Python


**Nitpicks:**
https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/setup/?lang=python
`import logging` is only needed if they actually use logging (fyi)

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read/?lang=python
Use the Reader object to read manifest data from a file or stream and perform validation on the manifest store.  **(I would add a newline here)**
Use the json() method to return a JSON manifest report; If there are validation errors, the report includes a validation_status field.

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build/?lang=python
Not all comments start with an uppercase and end the sentend with a dot. Is it OK here or not?

2025-02-14 20:22 UTC, andrewhalle commented on docs/tasks/includes/_rust-setup.md
> +
nit: Remove this blank line? I like to group imports by std/external/crate

2025-02-14 20:22 UTC, andrewhalle commented on docs/tasks/includes/_rust-setup.md
> +const TEST_IMAGE: &[u8] = include_bytes!("../tests/fixtures/CA.jpg");
It's not clear to me where to acquire these files. Should we provide a tarball for someone to download and extract?

2025-02-14 20:22 UTC, andrewhalle commented on docs/tasks/includes/_rust-read.md
> +Use the [`Reader`](https://docs.rs/c2pa/latest/c2pa/struct.Reader.html) struct to read manifest data from a file or stream.
This is a tangent. Please feel free to ignore.

I don't know how much control you have over the style, but these links are rendering sort of hard to read for me. The underline is too close to the text, and links are usually a different color, like blue.

![Screenshot 2025-02-14 at 12 16 48 PM](https://github.com/user-attachments/assets/1d9da88f-b9c1-4a13-ba8f-851dc154d73f)

Compare how `rustdoc` renders links.

![Screenshot 2025-02-14 at 12 18 46 PM](https://github.com/user-attachments/assets/ec47bff7-16db-4c3d-967a-1542e0a26500)

2025-02-14 20:22 UTC, andrewhalle commented on docs/tasks/includes/_rust-read.md
> +use c2pa::Reader;
Spacing between imports and code?

2025-02-14 22:43 UTC, crandmck commented
Thanks @tmathern I addressed your comments.

2025-02-14 22:51 UTC, crandmck commented on docs/tasks/includes/_rust-read.md
> +Use the [`Reader`](https://docs.rs/c2pa/latest/c2pa/struct.Reader.html) struct to read manifest data from a file or stream.
This is an orthogonal discussion, but we can certainly look at the visual design of the site...   We do have complete control over it.

FWIW, its been this way since its launch in 2022 based on work that Kozma and Pia did.  I suspect they didn't really consider the display of links on monospace (i.e. code) font text, and I agree it could use a bit more space between the underline and text.

2025-02-14 23:02 UTC, crandmck commented on docs/tasks/includes/_rust-setup.md
> +
Removed.

2025-02-14 23:04 UTC, andrewhalle approved these changes

2025-02-14 23:05 UTC, crandmck commented on docs/tasks/includes/_rust-setup.md
> +const TEST_IMAGE: &[u8] = include_bytes!("../tests/fixtures/CA.jpg");
I added a "tip" about where these files are located in the Rust repo. Do you think we should change the path in the code to something else?  This code is copied from https://github.com/contentauth/c2pa-rs/blob/main/sdk/tests/v2_api_integration.rs#L33.

2025-02-14 23:05 UTC, crandmck commented on docs/tasks/includes/_rust-read.md
> +use c2pa::Reader;
Fixed, if I understand your comment correctly.

2025-02-20 18:37 UTC, tmathern commented
https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build/?lang=python : `FROM SIGNING` is all lower case in the doc, but I think that's not right.

Otherwise, LGTM.

2025-02-20 23:45 UTC, crandmck commented
> I'm not sure what wasm support means with the check boxes. The almost the entire SDK supports wasm. The only major gap is openSSL signing and verification for ES512. Does that column mean JavaScript?

@cdmurph32 I'm not sure what you're referring to, perhaps the [Rust release notes](https://deploy-preview-176--cai-open-source.netlify.app/docs/rust-sdk/docs/release-notes#language-binding-support)...? There's nothing like that in this PR.

I'm asking you to review these pages (please refer to the PR description for the corresponding files):

- Setup: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/setup/?lang=node
- Reading manifest data: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read?lang=node
- Getting resources from a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources?lang=node. **_NOTE: This does not have any code currently, because I couldn't find an example or test code anywhere_**.
- Attaching and signing a manifest: https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build?lang=node

2025-02-21 00:04 UTC, crandmck commented
> https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build/?lang=python : `FROM SIGNING` is all lower case in the doc, but I think that's not right.

Oops, that whole section was essentially a duplicate of the previous code block, that I forgot to remove.... I deleted it, so it should look better now.

2025-02-21 00:14 UTC, tmathern approved these changes

2025-02-21 16:59 UTC, emensch commented on docs/tasks/includes/_js-setup.md
This setup works, but I think it would be useful to demonstrate how to include the library when installed locally (e.g. via `npm`). For the library itself, that just looks like:
```javascript
import { createC2pa } from 'c2pa':
```
But it gets a little tricker for the `wasmSrc` and `workerSrc`, which need to be made available as static assets that can be fetched at runtime. The best way to do that will vary depending on the build system. For example, vite has an ["explicit URL imports" feature](https://vite.dev/guide/assets#explicit-url-imports) that we use in our [`minimal-ts-vite` example](https://github.com/contentauth/c2pa-js/blob/main/examples/minimal-ts-vite/examples/active-manifest/main.ts#L2-L14).

2025-02-21 21:29 UTC, tmathern commented
For nodejs:

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/setup/?lang=node
- `import { readFile } from 'node:fs/promises';` looks unusual, but if it's in our code this way and works I would leave it (more usual is `... from fs.promises`)

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/read/?lang=node
- You may want to add that the `path` param needs to be a valid path (since we don't revalidate in the example), and `mimeType` a valid and supported mimetype (again because in the example we don't revalidate and/or check for undefined/null)

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/build/?lang=node
- `FROM SIGNING` is all uppercase somewhere in that page.
- `If you have an asset file's data loaded into memory, you can sign the the asset using the loaded stream (buffer)`. Streams are more native for node (and js), so you can be a little shorter here in the explanation: `If you have an asset file's data loaded into a stream, you can use it to sign the asset`

https://deploy-preview-176--cai-open-source.netlify.app/docs/tasks/get-resources/?lang=node
- I didn't find examples/test either. But if we want to showcase it, I think we can get inspiration from the js code (the first few lines).

cc @cdmurph32

2025-03-10 21:21 UTC, emensch commented on docs/tasks/includes/_js-setup.md
> +If you installed the package locally, for example from npm, then its simply:
tiny typo - `its` -> `it's`

2025-03-10 21:31 UTC, emensch commented on docs/tasks/includes/_node-wip.md
> +:::
Perhaps we should include a similar message about the JS library?

2025-03-10 21:32 UTC, emensch approved these changes

2025-03-10 21:43 UTC, crandmck commented on docs/tasks/includes/_node-wip.md
> +:::
Added!

2026-04-13 20:25 UTC, ok-nick reviewed
Reviewed Rust get-resources, read, and build.

2026-04-13 20:25 UTC, ok-nick commented on docs/tasks/rust/_rust-read.md
> +```
This seems redundant with the first example. They are both reading from a stream, in this case a file.

2026-04-13 20:25 UTC, ok-nick commented on docs/tasks/rust/_rust-read.md
> +There is also a deprecated asynchronous version, [`from_stream_async`](https://docs.rs/c2pa/latest/c2pa/struct.Reader.html#method.from_stream_async).
`from_stream_async` isn't deprecated, at least not yet. `with_stream_async` is perfectly fine to use instead of `with_stream`. I think we should remove this comment for clarity.

2026-04-13 20:25 UTC, ok-nick commented on docs/tasks/rust/_rust-get-resources.md
> +    let stream = std::fs::File::open("path/to/file.jpg")?;
```suggestion
use std::{fs::File, io::Cursor};

fn main() -> Result<()> {
    let context = Context::new();
    let stream = File::open("path/to/file.jpg")?;
```

2026-04-13 20:25 UTC, ok-nick commented on docs/tasks/rust/_rust-get-resources.md
> +    }
I think it would be better to show writing the thumbnail to a file.
```suggestion
    if let Some(manifest) = reader.active_manifest() {
        if let Some(thumbnail_ref) = manifest.thumbnail_ref() {
            let output_path = format!("thumbnail.{}", thumbnail_ref.format);
            let mut output_file = File::create(output_path)?;
            reader.resource_to_stream(&thumbnail_ref.identifier, &mut output_file)?;
        }
    }
```

2026-04-13 20:25 UTC, ok-nick commented on docs/tasks/rust/_rust-build.md
> +        .with_settings(include_str!("config.json"))?;
For clarity you can do:
```suggestion
    let settings = json!({
        "signer": {
            "local": {
                "alg": "ps256",
                "sign_cert": "path/to/cert.pem",
                "private_key": "path/to/key.pem",
                "tsa_url": "http://timestamp.digicert.com"
            }
        },
        "builder": {
            "claim_generator_info": { "name": "My App", "version": "1.0" },
            "intent": { "Create": "digitalCapture" }
        }
    });
    
    let context = Context::new()
        .with_settings(settings)?;
```

2026-04-13 20:53 UTC, crandmck commented on docs/tasks/rust/_rust-read.md
> +There is also a deprecated asynchronous version, [`from_stream_async`](https://docs.rs/c2pa/latest/c2pa/struct.Reader.html#method.from_stream_async).
Removed.  I thought it was going to be deprecated in https://github.com/contentauth/c2pa-rs/pull/2032 but now I don't see it.

2026-04-13 20:53 UTC, crandmck commented on docs/tasks/rust/_rust-read.md
> +```
Added what I hope is a better example

2026-04-13 21:07 UTC, ok-nick approved these changes

2026-04-13 21:07 UTC, ok-nick commented on docs/tasks/rust/_rust-read.md
> +```
I think we should remove the second example and rename the first one to "reading from a file or stream."

2026-04-13 21:07 UTC, ok-nick commented on docs/tasks/rust/_rust-get-resources.md
> +    }
My suggestion is wrong, actually. The format is the mime type, not the extension. Let's go back to what you originally had:
```suggestion
    if let Some(manifest) = reader.active_manifest() {
        if let Some(thumbnail_ref) = manifest.thumbnail_ref() {
            let mut thumbnail = Cursor::new(Vec::new());
            reader.resource_to_stream(&thumbnail_ref.identifier, &mut thumbnail)?;
            println!(
                "wrote thumbnail {} of size {}",
                thumbnail_ref.format,
                thumbnail.get_ref().len()
            );
        }
    }
```

2026-04-13 21:07 UTC, ok-nick commented on docs/tasks/rust/_rust-build.md
> +```
This can be removed now since we define it above.
```suggestion
```

2026-04-13 21:41 UTC, merged